version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  onln_postgres:
    image: postgres:9.6
    container_name: onln_postgres
    volumes:
      - $PWD/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=1234
      - POSTGRES_PASSWORD=onln
      - POSTGRES_USER=onln
      - POSTGRES_DB=onln
      - POSTGRES_INITDB_ARGS="--encoding=LATIN9"
    networks:
      - net
  oel7_system:
    container_name: oel7-system
    image: oel7-system
    build:
      context: oel7
    networks:
      - net
networks:
  net:

